apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3-awscli-app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "s3-awscli-app.name" . }}
    helm.sh/chart: {{ include "s3-awscli-app.chart" . }}
spec:
  replicas: {{ .Values.application.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "s3-awscli-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "s3-awscli-app.name" . }}
    spec:
      serviceAccountName: {{ include "s3-awscli-app.name" . }}
      containers:
      - name: aws-cli
        image: amazon/aws-cli:2.13.2
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            echo "This is a test file" > test.txt
            aws s3 cp test.txt s3://$BUCKET_NAME/
            while true; do aws s3 ls s3://$BUCKET_NAME/; sleep 120; done
        {{ template "application.resources" . }}
        env:
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "s3-awscli-app.name" . }}
              key: bucketName
      restartPolicy: Always