apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcd-crossplane
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  sources:
  - chart: kcd-crossplane
    repoURL: public.ecr.aws/g0f5w9v3/kcd-crossplane
    targetRevision: 0.0.1
    helm:
      valueFiles:
      - $values/argocd/values.yaml
  - repoURL: https://github.com/craftech-inc/kcd-2024-crossplane-argocd.git
    targetRevision: chore/test-argocd-app
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true